#!/bin/bash

# Variables
PROJECT_ID="golden-totality-429517-s7"
COMPUTE_ZONE="asia-east1-a"
CLUSTER_NAME="rk-cluster-01"
NUM_NODES=2
NODE_NAME_PREFIX="rk-node-01"
MACHINE_TYPE="e2-medium"
VPC_NAME="my-vpc001"
SUBNET_NAME="my-vpc001"
REGION="asia-east1"
NODE_LABEL="namespace=rk-lable-node-01"
MAX_PODS_PER_NODE=80  # Define the maximum number of pods per node

# Set the project
gcloud config set project $PROJECT_ID

# Set the compute zone
gcloud config set compute/zone $COMPUTE_ZONE

# Enable required services
gcloud services enable container.googleapis.com
gcloud services enable logging.googleapis.com
gcloud services enable monitoring.googleapis.com

# Create the GKE cluster
gcloud container clusters create $CLUSTER_NAME \
  --zone $COMPUTE_ZONE \
  --num-nodes $NUM_NODES \
  --machine-type $MACHINE_TYPE \
  --network $VPC_NAME \
  --subnetwork $SUBNET_NAME \
  --enable-ip-alias \
  --max-pods-per-node $MAX_PODS_PER_NODE \
  --labels $NODE_LABEL \
  --enable-stackdriver-kubernetes \
  --disk-type=pd-standard \
  --disk-size=70GB \
  --node-locations $COMPUTE_ZONE \
  --metadata disable-legacy-endpoints=true

# Get credentials for kubectl
gcloud container clusters get-credentials $CLUSTER_NAME --zone $COMPUTE_ZONE
